permalinks: pretty
sass:
  style: expanded

# kramdown:
#   parse_block_html: true

collections:
  course-content:
    output: true
    permalink: /:collection/:path/
  exercises:
    output: true
    permalink: /deliverables/:collection/:path/
  assignments:
    output: true
    permalink: /deliverables/:collection/:path/
  discussions:
    output: false
    permalink: /deliverables/:collection/:path/
  quizzes:
    output: false
    permalink: /deliverables/:collection/:path/
